# Generated by Django 3.2.3 on 2021-05-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_todo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nitrogen', models.CharField(blank=True, max_length=20, null=True)),
                ('Phosphorous', models.CharField(blank=True, max_length=20, null=True)),
                ('Potassium', models.CharField(blank=True, max_length=20, null=True)),
                ('Temperature', models.CharField(blank=True, max_length=20, null=True)),
                ('Humidity', models.CharField(blank=True, max_length=20, null=True)),
                ('Ph', models.CharField(blank=True, max_length=20, null=True)),
                ('Rainfall', models.CharField(blank=True, max_length=20, null=True)),
                ('Suitable_crop', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
