# Generated by Django 3.2.3 on 2021-05-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_contribute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
